### ISSUE TITLE
Scoreboard error

### ISSUE THREAD

**Issue by FeelTheLemon** [JetBoom/fretta13#11]
When clicking multiple times or pressing LMB on player name in scoreboard and moving cursor got this error:

> [ERROR] lua/vgui/dlistview_line.lua:118: attempt to call method 'ApplySchemeSettings' (a nil value)
> 1. SetSelected - lua/vgui/dlistview_line.lua:118
>    1. OnClickLine - lua/vgui/dlistview.lua:494
>    2. unknown - lua/vgui/dlistview_line.lua:104

According to [wiki](http://wiki.garrysmod.com/page/Category:DListView), DListView and DListView_Column is a parent of DPanel, so it must have a `ApplySchemeSettings` method.

**Comment by FeelTheLemon** [comment]
Found that commenting 
`Derma_Hook( PANEL, 	"ApplySchemeSettings", 	"Scheme", 	"SpectatorInfo" )` 
in _vgui_scoreboard.lua_, _vgui_scoreboard_small.lua_ and _vgui_scoreboard_team.lua_ fixes this error.
Not shure, but maybe this is the fix?

**Comment by Volantarius** [comment]
I have found the issue! Horray!

Adding `self.List:SetMultiSelect( false )` in `vgui\vgui_scoreboard_team.lua` Line 50, will prevent selecting the player lines.

`function PANEL:Init()

	self.Columns = {}
	
	self.List = vgui.Create( "DListView", self )
	self.List:SetSortable( false )
	self.List:DisableScrollbar()
	self.List:SetMultiSelect( false )-- <-- This right here
	
	self.Header = vgui.Create( "TeamScoreboardHeader", self )

end`
