### ISSUE TITLE
spectator name does not show when switching in new fretta

### ISSUE THREAD

**Issue by raymond4400** [JetBoom/fretta13#3]
In prop hunt

For some reason when you switch to spectator team now it shows nothing lol

Example: player joined _________

But if you join hunter or props it works correctly.

It worked fine before until the net changes.

**Comment by JetBoom** [comment]
e987403110d70c9c118d0a9fb39d46b76206f16c

**Comment by JetBoom** [comment]
1002 is indeed above 256
