### ISSUE TITLE
Error when voting gamemode

### ISSUE THREAD

**Issue by Jackralph96** [JetBoom/fretta13#4]
[ERROR] gamemodes/fretta13/gamemode/vgui/vgui_vote.lua:76: bad argument #1 to 'SetText' (string expected, got nil)
  1. SetText - [C]:-1
   2. ChooseGamemode - gamemodes/fretta13/gamemode/vgui/vgui_vote.lua:76
    3. ShowGamemodeChooser - gamemodes/fretta13/gamemode/cl_gmchanger.lua:30
     4. unknown - LuaCmd:1

Get this error when voting for a gamemode and it shows a button saying "Label" over the other gamemodes in the list.

**Comment by JetBoom** [comment]
Gamemodes need a "label" member in their gamemode txt file. Changed to fallback on folder name if it doesn't exist.
